<?php

return [
    'left' => [
        'How does the AI-powered writing assistant work?' => 'Our AI writing assistant uses advanced natural language processing and
                            machine learning algorithms to understand user inputs and generate human-like text. It
                            analyzes context, learns from patterns, and creates relevant, engaging content based on the
                            prompts or information provided.',
        'Can I try the AI writing assistant before committing to a plan?' => 'Yes, we offer a free trial so you can experience the capabilities of
                            our AI writing tool firsthand. Simply sign up on our website to get started.',
        'Is the content generated by the AI writing tool SEO-friendly?' => 'Yes, our AI writing assistant can create SEO-optimized content to help
                            improve your search engine rankings. Make sure to provide relevant keywords, and the tool
                            will incorporate them into the generated content.',
        'Will the AI-generated content be unique, or is there a risk of plagiarism?' => 'Our AI writing assistant is designed to generate unique content.
                            However, as with any automated tool, there is a slight chance of similarity with existing
                            content. We recommend checking the generated text for originality using a plagiarism
                            detection tool before publishing.',
    ],


    'right' => [
        'How does the credit system work for the AI writing tool?' => 'Our credit system is based on the number of words generated by the AI
                            writing assistant. Each credit corresponds to one word. Your plan determines the total
                            number of credits available to you, which get consumed as you use the tool to create
                            content.',
        'How do I provide input or prompts to the AI writing assistant?' => 'Simply type your desired prompt, topic, or keywords into the input field, and the AI writing
                            tool will generate content based on the information provided. You can also adjust settings
                            to fine-tune the output according to your preferences.',
        'Can I use the AI writing tool to create content in multiple languages?' => 'Yes, our AI-powered writing assistant supports multiple languages.',
        'Is the AI writing tool suitable for my specific industry or niche?' => 'Absolutely! Our AI-powered writing assistant is designed to adapt to
                            various industries and niches. Simply provide context and relevant information, and the tool
                            will generate content tailored to your specific needs.',
    ]

];
